### ISSUE TITLE
These Are Old

### ISSUE THREAD

**Issue by TheDarknessSurroundsYou** [Githubman6996/Blooket-hacks-minesraft2-deleted-before-he-got-terminated-and-05konx-deleted-or-just-hard-to-find#7]
https://gitlab.com/blooket/blooket-cheats/-/tree/main/cheats?ref_type=heads
05Konz's New Repo

**Comment by Githubman6996** [comment]
I know they are old I’m just reuploading the ones that were removed or are hard to find and a few custom ones

**Comment by Githubman6996** [comment]
@TheDarknessSurroundsYou
